apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-app
  labels:
    app: platform-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-app
                port:
                  number: 3000
